services:
    minio:
        container_name: minio
        image: minio/minio
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
            MINIO_DOMAIN: minio
        networks:
            iceberg:
                aliases:
                    - warehouse.minio
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - ./data/minio:/data
        entrypoint: sh
        command: -c 'mkdir -p /data/warehouse && minio server /data --console-address ":9001"'

    irest:
        container_name: irest
        image: tabulario/iceberg-rest
        environment:
            CATALOG_WAREHOUSE: s3://warehouse/
            CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
            CATALOG_S3_ENDPOINT: http://minio:9000
            AWS_ACCESS_KEY_ID: minioadmin
            AWS_SECRET_ACCESS_KEY: minioadmin
            AWS_REGION: us-east-1
        networks:
            iceberg:
        ports:
            - 8181:8181

    maria:
        container_name: maria
        image: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - ./data/maria:/var/lib/mysql

networks:
  iceberg:

