services:
    maria:
        container_name: maria
        image: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - ./data:/var/lib/mysql

